using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace GroceryManagementSystem
{
    public partial class FormUser : Form
    {
        private readonly UsersFunction _parent;
        public FormUser(UsersFunction parent)
        {
            InitializeComponent();
            _parent = parent;
        }

        private void btnHide_Click(object sender, EventArgs e)
        {
            WindowState = FormWindowState.Minimized;
        }

        private void btnMaximize_Click(object sender, EventArgs e)
        {

            if (WindowState == FormWindowState.Normal)
            {
                WindowState = FormWindowState.Maximized;
            }
            else
            {
                WindowState = FormWindowState.Normal;

            }
        }

        private void btnClose_Click(object sender, EventArgs e)
        {
            Application.Exit();
        }

        private void Clear()
        {
            textBoxUsername.Text = textBoxPassword.Text = textBoxIsadmin.Text = textBoxEmail.Text = string.Empty;
        }

        private void SaveButton_Click(object sender, EventArgs e)
        {
            // Retrieve user data from the form
            string username = textBoxUsername.Text;
            string password = textBoxPassword.Text;
            bool Isadmin = false; // Default to false
            if (textBoxIsadmin.Text.Trim() == "1") // Check if the input is "1"
            {
                Isadmin = true; // Set to true if input is "1"
            }
            string email = textBoxEmail.Text;

            // Create a new User object without specifying User_ID
            User newUser = new User(0,username, password, Isadmin, email); // User_ID will be auto-generated by the database

            // Call the AddUser method from DbUser to save the user data to the database
            DbUser.AddUser(newUser);

            // display a message or perform other actions after saving the user
            MessageBox.Show("User saved successfully!", "Success", MessageBoxButtons.OK, MessageBoxIcon.Information);

            // you can refresh the DataGridView in the parent form to reflect the new user
            _parent.Display();

            // Close the form 
            this.Close();
        }
    }

}

